use std::os::unix::fs::FileTypeExt;
use std::{fs::DirEntry, os::unix::fs::MetadataExt};

use crate::constraints;
use crate::tokenizer::Tokens;

// ! & (& c d) (& a ! b)

fn parse_not(operands_stack: &mut Vec<crate::operators::Operators<DirEntry>>) -> Result<crate::operators::Operators<DirEntry>, String> {
    operands_stack.pop().map(crate::operators::Operators::not).ok_or("Missing operand for operator: !".to_string())
} 

fn parse_and(operands_stack: &mut Vec<crate::operators::Operators<DirEntry>>) -> Result<crate::operators::Operators<DirEntry>, String> {
    match (operands_stack.pop(), operands_stack.pop()) {
        (Some(lhs), Some(rhs)) => Ok(lhs.and(rhs)),
        _ => Err("Missing operand for operator: &".to_string()),
    }
} 

fn parse_or(operands_stack: &mut Vec<crate::operators::Operators<DirEntry>>) -> Result<crate::operators::Operators<DirEntry>, String> {
    match (operands_stack.pop(), operands_stack.pop()) {
        (Some(lhs), Some(rhs)) => Ok(lhs.or(rhs)),
        _ => Err("Missing operand for operator: |".to_string()),
    }
} 

fn parse_xor(operands_stack: &mut Vec<crate::operators::Operators<DirEntry>>) -> Result<crate::operators::Operators<DirEntry>, String> {
    match (operands_stack.pop(), operands_stack.pop()) {
        (Some(lhs), Some(rhs)) => Ok(lhs.xor(rhs)),
        _ => Err("Missing operand for operator: ^".to_string()),
    }
} 

fn parse_biconditional(operands_stack: &mut Vec<crate::operators::Operators<DirEntry>>) -> Result<crate::operators::Operators<DirEntry>, String> {
    match (operands_stack.pop(), operands_stack.pop()) {
        (Some(lhs), Some(rhs)) => Ok(lhs.biconditional(rhs)),
        _ => Err("Missing operand for operator: =".to_string()),
    }
} 

fn parse_conditional(operands_stack: &mut Vec<crate::operators::Operators<DirEntry>>) -> Result<crate::operators::Operators<DirEntry>, String> {
    match (operands_stack.pop(), operands_stack.pop()) {
        (Some(lhs), Some(rhs)) => Ok(lhs.conditional(rhs)),
        _ => Err("Missing operand for operator: ~".to_string()),
    }
} 


fn parse_operator(operands_stack: &mut Vec<crate::operators::Operators<DirEntry>>, operator: &crate::tokenizer::OperatorKind) -> Result<crate::operators::Operators<DirEntry>, String> {
    match operator {
        crate::tokenizer::OperatorKind::Not => parse_not(operands_stack),
        crate::tokenizer::OperatorKind::And => parse_and(operands_stack),
        crate::tokenizer::OperatorKind::Or => parse_or(operands_stack),
        crate::tokenizer::OperatorKind::Xor => parse_xor(operands_stack),
        crate::tokenizer::OperatorKind::Conditional => parse_conditional(operands_stack),
        crate::tokenizer::OperatorKind::Biconditional => parse_biconditional(operands_stack),
    }
}



pub fn parse_predicate<T: Into<Vec<Tokens>>>(predicate: T) -> Result<crate::operators::Operators<DirEntry>, String> {
    let mut tokens = predicate.into();
    
    let mut operands: Vec<crate::operators::Operators<DirEntry>> = Vec::new();

    while let Some(token) = tokens.pop() {
        match token {
            crate::tokenizer::Tokens::Operand(operand) => operands.push(crate::operators::Operators::try_from(&operand)?),
            crate::tokenizer::Tokens::Operator(operator) => {
                let operand = parse_operator(&mut operands, &operator)?;
                operands.push(operand)
            }
        }
    }
    let operands_length = operands.len();
    if operands_length  != 1 {
        return Err(format!("Something went wrong while parsing the predicate: maybe empty predicate provided or one ore more extra operands provided/misplaced"))
    } 

    Ok(operands.pop().unwrap())
}



pub(crate) fn create_size_constraint(constraint: &str) -> Result<Box<dyn  Fn(&DirEntry) -> bool + 'static>, String> {
    if constraint.len() < 2 {
        return Err(format!("Invalid Size constraint token: {constraint} "));
    }
    let (op, size_str) = crate::constraints::parse_op(constraint)?;
    let size = crate::constraints::parse_size(size_str)?;

    let requirement = crate::constraints::apply_op(op, size);

    Ok(Box::new(
        move |entry: &DirEntry| entry.metadata().map_or(false, |meta| requirement(meta.size()))
    ))
}

/// Dock string generated by Claude Sonnet 4.6
/// Accepts entries matching ANY of the specified types.
/// 'f' = file, 'd' = directory, 'l' = symlink,
/// 'c' = char device, 'b' = block device,
/// 'p' = pipe, 's' = socket
/// Example: "fd" matches files and directories
pub(crate) fn create_type_constraint(constraint: &str) -> Result<Box<dyn Fn(&DirEntry) -> bool + 'static>, String> {
    if constraint.is_empty() {
        return Err("No type provided for type constraint".to_string());
    }

    // collect all required methods into one vector and then call them. If any one of them returns true, the entry is accepted
    let mut file_types: Vec<fn(&std::fs::FileType) -> bool> = Vec::new();

    for type_char in constraint.chars() {
        match type_char {
            'f' => file_types.push(std::fs::FileType::is_file),
            'd' => file_types.push(std::fs::FileType::is_dir),
            'l' => file_types.push(std::fs::FileType::is_symlink),
            'c' => file_types.push(std::fs::FileType::is_char_device),
            'b' => file_types.push(std::fs::FileType::is_block_device),
            'p' => file_types.push(std::fs::FileType::is_fifo),
            's' => file_types.push(std::fs::FileType::is_socket),
            t => return Err(format!("unrecognized entry type in {constraint}: {t}"))
        }
    };

    let filetype_check = move |filetype: &std::fs::FileType| file_types.iter().any(|filetype_constraint| filetype_constraint(filetype));
    Ok(Box::new(move |entry: &DirEntry| entry.metadata().map_or(false, |meta| filetype_check(&meta.file_type()))))
}


pub(crate) fn create_name_constraint(constraint: &str) -> Result<Box<dyn Fn(&DirEntry) -> bool + 'static>, String> {
    if constraint.is_empty() {
        return Err("No name provided for name constraint".to_string());
    }

    let pattern = regex::Regex::new(constraint).map_err(|e| format!("regex creation error: {e}"))?;

    let check_name = move |name: &str| pattern.is_match(name);

    Ok(Box::new(move |entry: &DirEntry| entry.file_name().to_str().map_or(false, |name| check_name(name))))
}


/// Dock string generated by Claude Sonnet 4.6
/// Creates a constraint that matches entries whose file extension equals the given string.
///
/// # Arguments
/// * `constraint` - The file extension to match against, without the leading dot (e.g. "toml", "rs")
///
/// # Returns
/// A boxed closure that returns `true` if the entry's extension matches, `false` otherwise.
///
/// # Behavior
/// - Entries without an extension (directories, sockets, pipes, files without extensions) are rejected
/// - Matching is case sensitive
/// - The leading dot is handled automatically via [`Path::extension`] — do not include it in `constraint`
pub(crate) fn create_ext_constraint(constraint: &str) -> Result<Box<dyn Fn(&DirEntry) -> bool + 'static>, String> {
    if constraint.is_empty() {
        return Err("No extension provided for extension constraint".to_string());
    }

    let extension_pattern = regex::Regex::new(constraint).map_err(|e|format!("Error creating regex for extension matching: {e}"))?;

    let check_extension = move |ext: &str| extension_pattern.is_match(ext); 

    Ok(Box::new(move |entry: &DirEntry| entry.path().extension().and_then(|ext| ext.to_str()).map_or(false, |ext| check_extension(ext))))
}

pub(crate) fn create_misc_constraint(constraint: &str) -> Result<Box<dyn Fn(&DirEntry) -> bool + 'static>, String> {
    if constraint.is_empty() {
        return Err("No property provided to match against".to_string());
    }

    Ok(Box::new(crate::constraints::parse_misc(constraint)?))
}

pub(crate) fn create_perm_constraint(constraint: &str) -> Result<Box<dyn Fn(&DirEntry) -> bool + 'static>, String> {
    Ok(Box::new(crate::constraints::parse_perm(constraint)?))
}

fn parse_time_constraint(constraint: &str) -> Result<u64, String> {
    let mut constraint = constraint;
    todo!()
}

pub(crate) fn create_atime_constraint(constraint: &str) -> Result<Box<dyn Fn(&DirEntry) -> bool + 'static>, String> {
    todo!()
}
